services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER: maihoon
      - POSTGRES_PASSWORD: wahitohai
      - POSTGRES_DB: goauth

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: