name: Deploy Go API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Verify Go
        run: go version

      - name: Download Dependencies
        run: go mod tidy

      - name: Create .env
        run: |
          cat > .env << EOF
          PORT=${{ secrets.PORT }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          JWT_EXPIRE_HOURS=${{ secrets.JWT_EXPIRE_HOURS }}
          EOF

      - name: Build Binary
        run: |
          mkdir dist
          go build -o goauth ./cmd

      - name: Upload Binary
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./"
          target: "/home/ubuntu/goauth/"

     