name: Go CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Verify Go
        run: go version

      - name: Download Dependencies
        run: go mod tidy

      - name: Build Application
        run: go build -o goauth ./cmd
     